#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RentToGo.Resource", IsApplication=true)]

namespace RentToGo
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::RentToGo.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.font = global::RentToGo.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::RentToGo.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::RentToGo.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::RentToGo.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::RentToGo.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::RentToGo.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::RentToGo.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::RentToGo.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::RentToGo.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::RentToGo.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::RentToGo.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::RentToGo.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::RentToGo.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::RentToGo.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::RentToGo.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::RentToGo.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::RentToGo.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::RentToGo.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::RentToGo.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::RentToGo.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::RentToGo.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::RentToGo.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::RentToGo.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::RentToGo.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::RentToGo.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::RentToGo.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::RentToGo.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::RentToGo.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::RentToGo.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::RentToGo.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::RentToGo.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::RentToGo.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::RentToGo.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::RentToGo.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::RentToGo.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::RentToGo.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::RentToGo.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::RentToGo.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::RentToGo.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::RentToGo.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::RentToGo.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::RentToGo.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::RentToGo.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::RentToGo.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::RentToGo.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::RentToGo.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::RentToGo.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::RentToGo.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::RentToGo.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.actions = global::RentToGo.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::RentToGo.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::RentToGo.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::RentToGo.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::RentToGo.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.async = global::RentToGo.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::RentToGo.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::RentToGo.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::RentToGo.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::RentToGo.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::RentToGo.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::RentToGo.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::RentToGo.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::RentToGo.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::RentToGo.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::RentToGo.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::RentToGo.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::RentToGo.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::RentToGo.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::RentToGo.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::RentToGo.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::RentToGo.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::RentToGo.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::RentToGo.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::RentToGo.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::RentToGo.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::RentToGo.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::RentToGo.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::RentToGo.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::RentToGo.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::RentToGo.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::RentToGo.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::RentToGo.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::RentToGo.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::RentToGo.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::RentToGo.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::RentToGo.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::RentToGo.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::RentToGo.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::RentToGo.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::RentToGo.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::RentToGo.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::RentToGo.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::RentToGo.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::RentToGo.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::RentToGo.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::RentToGo.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::RentToGo.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::RentToGo.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::RentToGo.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::RentToGo.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::RentToGo.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::RentToGo.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::RentToGo.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::RentToGo.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::RentToGo.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::RentToGo.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::RentToGo.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::RentToGo.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::RentToGo.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::RentToGo.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::RentToGo.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::RentToGo.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::RentToGo.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::RentToGo.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::RentToGo.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::RentToGo.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::RentToGo.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::RentToGo.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::RentToGo.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::RentToGo.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::RentToGo.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::RentToGo.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::RentToGo.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::RentToGo.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::RentToGo.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::RentToGo.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::RentToGo.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::RentToGo.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::RentToGo.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::RentToGo.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::RentToGo.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::RentToGo.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonSize = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorScheme = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int font = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderAuthority = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderCerts = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderFetchStrategy = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontProviderFetchTimeout = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontProviderPackage = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontProviderQuery = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int fontStyle = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fontVariationSettings = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fontWeight = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int imageAspectRatio = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int imageAspectRatioAdjust = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int scopeUris = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int ttcIndex = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int common_google_signin_btn_text_dark = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_google_signin_btn_text_dark_default = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_google_signin_btn_text_dark_disabled = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_google_signin_btn_text_dark_focused = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_google_signin_btn_text_dark_pressed = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_google_signin_btn_text_light = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_google_signin_btn_text_light_default = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_google_signin_btn_text_light_disabled = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int common_google_signin_btn_text_light_focused = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int common_google_signin_btn_text_light_pressed = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int common_google_signin_btn_tint = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ic_launcher_background = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int notification_action_color_filter = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int notification_icon_bg_color = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int ripple_material_light = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int secondary_text_default_material_light = 2130837522;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int fab_margin = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int notification_action_icon_size = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_action_text_size = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_big_circle_margin = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_content_margin_start = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_large_icon_height = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_large_icon_width = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_main_column_padding_top = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_media_narrow_margin = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_right_icon_size = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_right_side_padding_top = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_small_icon_background_padding = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_small_icon_size_as_large = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_subtext_size = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_top_pad = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int notification_top_pad_large_text = 2130903062;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int agent1 = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int agent2 = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int agent3 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int common_full_open_on_phone = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int common_google_signin_btn_icon_dark = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int common_google_signin_btn_icon_dark_focused = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int common_google_signin_btn_icon_dark_normal = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int common_google_signin_btn_icon_dark_normal_background = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int common_google_signin_btn_icon_disabled = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int common_google_signin_btn_icon_light = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int common_google_signin_btn_icon_light_focused = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int common_google_signin_btn_icon_light_normal = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int common_google_signin_btn_icon_light_normal_background = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int common_google_signin_btn_text_dark = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int common_google_signin_btn_text_dark_focused = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int common_google_signin_btn_text_dark_normal = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int common_google_signin_btn_text_dark_normal_background = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int common_google_signin_btn_text_disabled = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int common_google_signin_btn_text_light = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int common_google_signin_btn_text_light_focused = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int common_google_signin_btn_text_light_normal = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int common_google_signin_btn_text_light_normal_background = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int googleg_disabled_color_18 = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int googleg_standard_color_18 = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int house1 = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int house2 = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int house3 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int house4 = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int ic_launcher = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int notification_action_background = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int notification_bg = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int notification_bg_low = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int notification_bg_low_normal = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int notification_bg_low_pressed = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int notification_bg_normal = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int notification_bg_normal_pressed = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int notification_icon_background = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int notification_template_icon_bg = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int notification_template_icon_low_bg = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int notification_tile_bg = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int notify_panel_notification_icon_bg = 2130968616;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050001
			public const int accessibility_action_clickable_span = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int accessibility_custom_action_0 = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int accessibility_custom_action_1 = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int accessibility_custom_action_10 = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int accessibility_custom_action_11 = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int accessibility_custom_action_12 = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int accessibility_custom_action_13 = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int accessibility_custom_action_14 = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int accessibility_custom_action_15 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int accessibility_custom_action_16 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int accessibility_custom_action_17 = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int accessibility_custom_action_18 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int accessibility_custom_action_19 = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int accessibility_custom_action_2 = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int accessibility_custom_action_20 = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int accessibility_custom_action_21 = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int accessibility_custom_action_22 = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int accessibility_custom_action_23 = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int accessibility_custom_action_24 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int accessibility_custom_action_25 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int accessibility_custom_action_26 = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int accessibility_custom_action_27 = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int accessibility_custom_action_28 = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int accessibility_custom_action_29 = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int accessibility_custom_action_3 = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int accessibility_custom_action_30 = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int accessibility_custom_action_31 = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int accessibility_custom_action_4 = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int accessibility_custom_action_5 = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int accessibility_custom_action_6 = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int accessibility_custom_action_7 = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int accessibility_custom_action_8 = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int accessibility_custom_action_9 = 2131034145;
			
			// aapt resource value: 0x7F050028
			public const int actions = 2131034152;
			
			// aapt resource value: 0x7F050022
			public const int action_container = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int action_divider = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int action_image = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int action_search = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int action_settings = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int action_text = 2131034151;
			
			// aapt resource value: 0x7F050029
			public const int adjust_height = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int adjust_width = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int app_name = 2131034155;
			
			// aapt resource value: 0x7F050000
			public const int APP_NAME = 2131034112;
			
			// aapt resource value: 0x7F05002C
			public const int async = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int auto = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int blocking = 2131034158;
			
			// aapt resource value: 0x7F050030
			public const int btnShare = 2131034160;
			
			// aapt resource value: 0x7F05002F
			public const int btnSMS = 2131034159;
			
			// aapt resource value: 0x7F050031
			public const int chronometer = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int dark = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int dialog_button = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int fab = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int forever = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int icon = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int icon_group = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int icon_only = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int imgMapFrag = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int info = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int italic = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int light = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int line1 = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int line3 = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int mapFrgContainer = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int mask = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int none = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int normal = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int notification_background = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int notification_main_column = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int notification_main_column_container = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int right_icon = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int right_side = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int standard = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int tag_accessibility_actions = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public const int tag_accessibility_clickable_spans = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public const int tag_accessibility_heading = 2131034187;
			
			// aapt resource value: 0x7F05004C
			public const int tag_accessibility_pane_title = 2131034188;
			
			// aapt resource value: 0x7F05004D
			public const int tag_screen_reader_focusable = 2131034189;
			
			// aapt resource value: 0x7F05004E
			public const int tag_transition_group = 2131034190;
			
			// aapt resource value: 0x7F05004F
			public const int tag_unhandled_key_event_manager = 2131034191;
			
			// aapt resource value: 0x7F050050
			public const int tag_unhandled_key_listeners = 2131034192;
			
			// aapt resource value: 0x7F050051
			public const int text = 2131034193;
			
			// aapt resource value: 0x7F050052
			public const int text2 = 2131034194;
			
			// aapt resource value: 0x7F050053
			public const int time = 2131034195;
			
			// aapt resource value: 0x7F050054
			public const int title = 2131034196;
			
			// aapt resource value: 0x7F050055
			public const int toolbar = 2131034197;
			
			// aapt resource value: 0x7F050056
			public const int wide = 2131034198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int google_play_services_version = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int status_bar_notification_info_maxnum = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_main = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int content_main = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int custom_dialog = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int fragment_agent = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int list_House = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_action = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_action_tombstone = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_custom_big = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_template_icon_group = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_part_chronometer = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_part_time = 2131165194;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int bottom_navigation_main = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int menu_main = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int ic_launcher_foreground = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int ic_launcher_round = 2131296258;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int common_google_play_services_enable_button = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int common_google_play_services_enable_text = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int common_google_play_services_enable_title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int common_google_play_services_install_button = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int common_google_play_services_install_text = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int common_google_play_services_install_title = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int common_google_play_services_notification_channel_name = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int common_google_play_services_notification_ticker = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int common_google_play_services_unknown_issue = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int common_google_play_services_unsupported_text = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int common_google_play_services_update_button = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int common_google_play_services_update_text = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int common_google_play_services_update_title = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int common_google_play_services_updating_text = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int common_google_play_services_wear_update_text = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int common_open_on_phone = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int common_signin_button_text = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int common_signin_button_text_long = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int fcm_fallback_notification_channel_label = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int firebase_preference_file_key = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int installation_enrichment_file_key = 2131361814;
			
			// aapt resource value: 0x7F0A0017
			public const int status_bar_notification_info_overflow = 2131361815;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme_AppBarOverlay = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int AppTheme_NoActionBar = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int AppTheme_PopupOverlay = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int TextAppearance_Compat_Notification = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int TextAppearance_Compat_Notification_Info = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int TextAppearance_Compat_Notification_Time = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int TextAppearance_Compat_Notification_Title = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int Widget_Compat_NotificationActionContainer = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int Widget_Compat_NotificationActionText = 2131427338;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A }
			public static int[] FontFamily = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010004,0x7F01000B,0x7F01000C,0x7F01000D,0x7F010011 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771972,
					2130771979,
					2130771980,
					2130771981,
					2130771985};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x7F010002,0x7F01000E,0x7F01000F }
			public static int[] LoadingImageView = new int[] {
					2130771970,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010001,0x7F010003,0x7F010010 }
			public static int[] SignInButton = new int[] {
					2130771969,
					2130771971,
					2130771984};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0D0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131558400;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
